POST http://127.0.0.1:8000/login
Content-Type: application/json

{"username": "fcasaaa2", "password": "123"}

###

POST http://127.0.0.1:8000/signup
Content-Type: application/json

{"username": "fcasaaa2", "password": "123", "email": "fcas@gmail.com"}

###

GET http://127.0.0.1:8000/test_token
Content-Type: application/json
Authorization: Token 8d8997a8bbac0b888818a768999673488dba3bf1

{}